### PR TITLE
Added Schema for config.json

### PR DESCRIPTION
**Pull request by Murky-MoMo**
With this, #1 is pretty much resolved, the users now get intellisense for config.json, it would be useful if there was a readme.md telling the users what to do but after making a config.json, it's pretty much done for config.json

### CODE REVIEW

**Review by Ayeven — CHANGES_REQUESTED** [review]
I was simply going to make a simple `config.js.example`, not sure how this work as I never tried it before. I've come across [inquirer](https://www.npmjs.com/package/inquirer) before, example I can get from [here](https://github.com/AnIdiotsGuide/guidebot/blob/master/setup.js), which I think does almost same thing like this? As you can't see the my `config.js` file, there is 1 "parameter" left out, the owner/team id where in my case it will be `owner's id`  It is required by command exclusive to owner (eg. `deploy.js`). It is used for hiding the exclusive(s) command too using partition(using discordjs collection partition method) `owner/non owner` command(s) to hide owner only command from public, though I don't think I will make much normal command as slash command is far better than it. 
`config = {
  token:"Sometoken",
  owner:"Someid",
  prefix:";",
  intents: ["GUILDS","GUILD_MESSAGES","GUILD_WEBHOOKS","GUILD_VOICE_STATES"],
  partials: ["USER","GUILD_MEMBER","MESSAGE","REACTION"],
}`

**Comment by Murky-MoMo** [comment]
the owner id is something i thought of, in order to replicate what you already have and not prematurely add stuff, I didn't add that
What i did was searching the keyword `config` through the entire repository to see which values you access and then added those, adding owner won't be a hassle, it's just one more property 
as for the library "inquirer" that you bring up, it's very different than this implementation
this adds types to the json, like how you add types to the functions, meaning this adds intellisense


they have their own descriptions

And they also make some properties required


what inquirer does is that it just takes answers to a bunch questions from the terminal, and then it's still your job to implement it in a way that it'll save it to a file
what this still doesn't do is add the typings to the JSON, like after generating it, the user can't just change up the JSON, for ease, they'd need to go through the whole inquirer process to change it
nor does it error when there is a mistype in the json

**Comment by Murky-MoMo** [comment]
also before that, I'll just add the owner id on this pull request now instead of making another one
For that I have a few questions
- Is this a must-have? Does your code rely on this value existing? should this be enforced like how in the examples I made intents enforced?
- Is it an array? Does it take multiple IDs or does it only take one ID?

**Comment by Ayeven** [comment]
- must-have? Yes, it is required as a check so others can't execute `owner's exclusive command` and kept away hidden
- no, this is not an array as now. This is only single ID

**Comment by Murky-MoMo** [comment]
With that, owner was added!

**Comment by Ayeven** [comment]
Looking good!

**Pull request merged**
